baseURL: "https://quesignificamisueno.com/"
theme: "up-business-theme"
languageCode: "es-ar"

title: "Que Significa Mi Sueño?"

# googleAnalytics: ""

summaryLength: 20

params:
  title: "Que Significa Mi Sueño?"
  description: "Interpretaciónes de sueños."
  images: 
    - "images/hero-image.png"

  logo: "arrow-up.png"

  favicons:
    themeColor: "#FFFFFF"
    backgroundColor: "#FFFFFF"
    faviconColor: "#000000"

  # social:
  #   dribbble: "#"
  #   instagram: "#"
  #   facebook: "#"
  #   twitter: "#"

  # location:
  #   - "3891 Ranchview Dr. Richardson, California 62639"
  #   - "4517 Washington Ave. Manchester, Kentucky 39495"

  # contact:
  #   - "no-email@noop.aaa"
  #   - "555.555.5555"

  copyright: "© 2024 Piqo Labs"

menus:
  # main:
  #   - name: "Home"
  #     url: "/#hero"
  #     weight: 1

  #   - name: "How we work"
  #     url: "/#"
  #     weight: 2

  #   - name: "Our team"
  #     url: "/#"
  #     weight: 3

  #   - name: "Pricing"
  #     url: "/#"
  #     weight: 4

  #   - name: "Blog"
  #     url: "/blog"
  #     weight: 5

  # buttons:
  #   - name: "Book a call"
  #     url: "/#"
  #     weight: 5
  #     pre: "btn btn-primary text-light"

  # footer:
  #   - name: "Home"
  #     url: "/#hero"
  #     weight: 1

  #   - name: "How we work"
  #     url: "/#"
  #     weight: 2

  #   - name: "Our team"
  #     url: "/#"
  #     weight: 3

  #   - name: "Pricing"
  #     url: "/#"
  #     weight: 4

  #   - name: "Blog"
  #     url: "/blog"
  #     weight: 5

taxonomies:
  series: "series"
  tags: "tags"
